# Generated by Django 3.0 on 2021-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_nsedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsedata',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
