# Generated by Django 3.0 on 2022-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210904_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSESymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
