# Generated by Django 3.0 on 2022-03-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_nsesymbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsesymbol',
            name='isin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nsesymbol',
            name='series',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
