# Generated by Django 3.0 on 2022-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220325_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSEDailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField(max_length=20, null=True)),
                ('high', models.CharField(max_length=20, null=True)),
                ('low', models.CharField(max_length=20, null=True)),
                ('close', models.CharField(max_length=20, null=True)),
                ('last', models.CharField(max_length=20, null=True)),
                ('prev_close', models.CharField(max_length=20, null=True)),
                ('tot_trd_qty', models.CharField(max_length=20, null=True)),
                ('tot_trd_val', models.CharField(max_length=20, null=True)),
                ('tot_trd', models.CharField(max_length=20, null=True)),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
