# Generated by Django 3.0 on 2022-03-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_nsedailydata_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsedailydata',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.NSESymbol'),
        ),
    ]
